default: &default
  username: pguser
  password: pguser
  host: localhost
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: work_with_applications_development

test:
  <<: *default
  database: work_with_applications_test

production:
  <<: *default
  database: work_with_applications_production
  username: work_with_applications
  password: <%= ENV['WORK_WITH_APPLICATIONS_DATABASE_PASSWORD'] %>
